version: '3.8'

services:
  db:
    container_name: db
    image: mysql:latest
    env_file:
      - .env.docker-compose
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    working_dir: /var/www
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - .:/var/www
    depends_on:
      - api
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
